# Generated by Django 3.0.6 on 2020-05-20 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='parent_endpoint',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='endpoints.Endpoint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='feedback',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
